# Generated by Django 4.2 on 2023-05-19 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_processes_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processes',
            name='process_id',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message="Input must start with 'P' followed by two integers letters.", regex='^P[0-9]{2}$')]),
        ),
    ]
