# Generated by Django 4.2 on 2023-06-15 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_alter_processes_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='processes',
            name='priority',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
