# Generated by Django 4.2.9 on 2024-02-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_processes_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
