# Generated by Django 4.2.9 on 2024-02-12 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_alter_processes_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processes',
            name='id',
        ),
        migrations.AlterField(
            model_name='processes',
            name='process_id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Input must start with 'P' followed by two integers letters.", regex='^P[0-9]{2}$')]),
        ),
    ]
