# Generated by Django 4.2.9 on 2024-02-12 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_remove_processes_id_alter_processes_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='processes',
            name='p_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processes',
            name='process_id',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message="Input must start with 'P' followed by two integers letters.", regex='^P[0-9]{2}$')]),
        ),
    ]
